### ISSUE TITLE
Tutorial 2: TypeError

### ISSUE THREAD

**Issue by dtchang** [lcmd-epfl/MLKRR#1]
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_19020\1948509090.py in <module>
----> 1 model = mlkrr.MLKRR(
      2     verbose=True, shuffle_iterations=5,
      3     max_iter_per_shuffle=20, krr_regularization = 1e-9,
      4     size1=0.3, size2=0.7)

TypeError: __init__() got an unexpected keyword argument 'size1'

**Comment by Mattuuuuh** [comment]
We removed the tutorials and put new example scripts instead in the examples/ directory.
