### ISSUE TITLE
the current implementation is pretty memory hungry [improvement] [suggestion]

### ISSUE THREAD

**Issue by UnixJunkie** [lcmd-epfl/MLKRR#12]
I wonder if it would be possible to improve on that front:

Currently, I observe 20 GB of RAM being used while training on a rather smallish dataset
(160 datapoints w/ 4428 features each; and this is a sparse representation).

Maybe the problems comes from this:
- you only work w/ dense matrices while some molecular encoding (fingerprint based) are sparse.

**Comment by raimon-fa** [comment]
The algorithm needs to optimize a matrix with size Nfeatures x Nfeatures. The memory consumption come from here, not so much from the number of training points.
