### ISSUE TITLE
Up to how many dimensions is L-BFGS-B supposed to work? [question]

### ISSUE THREAD

**Issue by UnixJunkie** [lcmd-epfl/MLKRR#13]
Is there a recommended alternative in case we have more dimensions than that?

**Comment by raimon-fa** [comment]
As many dimensions as you have RAM for. The model needs to optimize an Nfeatures x Nfeatures matrix, which grows quickly.

**Comment by UnixJunkie** [comment]
Ok, so on modern computers it might be in the 100k to 300k dimensions.
