### ISSUE TITLE
The problem of mapping back to the original space after dimensionality reduction

### ISSUE THREAD

**Issue by yuChen-XD** [lcmd-epfl/MLKRR#3]
Hello, I would like to know if the dimensionality reduction data can be mapped back to the original space after using MLKR to reduce the dimensionality of the data? I've tried to map back to the original space without downgrading the dimension, but when I map the data back to the original space after downgrading, the number of columns in the L matrix is less than the number of rows and is irreversible? Can you give some comments on this?
Thank you for your help in advance!

**Comment by Mattuuuuh** [comment]
Which function reduces the dimension of the data exactly?
The data given to `fit` are the samples `X` (dim n-by-d) and labels `y` (dim n). These should always remain the same, while the metric `A` (dim d-by-d) is learned.
The modified samples `X@A.T` have the same dimensions as `X`. Its rank might decrease if `A` is not full-rank, which would mean that some features are not less important than others.

**Comment by yuChen-XD** [comment]
Hi! Thank u very much for your reply. I mean that the rank of X_map(X_map=X@A.T) will decrease if the A is not full-rank as you said. It seems that X_map can't be mapped back to the original space (dim d).
Thank u again for your help~
