### ISSUE TITLE
Would it be possible to replace the molecular encoding? [question]

### ISSUE THREAD

**Issue by UnixJunkie** [lcmd-epfl/MLKRR#4]
Hi there!

Currently, I understand the 3D-sensitive FCHL is being used.

I wonder if it would be doable to use any rdkit fingerprint instead.

Where should I be looking at to implement this change?

Thanks,
Francois.

**Comment by raimon-fa** [comment]
The algorithm takes data with a vectorial representation as input, which can be anything. It is not linked to FCHL or even to molecular representations.

**Comment by UnixJunkie** [comment]
Super cool, thanks!
