### ISSUE TITLE
Which exact python version was this tested on ? [question]

### ISSUE THREAD

**Issue by UnixJunkie** [lcmd-epfl/MLKRR#8]
I'd like to check if the requirements.txt file is supposed to work...
W/ Python-3.12.3, it doesn't.

**Comment by raimon-fa** [comment]
I think 3.7 or 3.8.

**Comment by UnixJunkie** [comment]
If you can confirm, that would be really helpful.
So that I can try to get the exact environment for a maximum reproducible
behavior.

**Comment by raimon-fa** [comment]
Sorry this work was done several years ago and I don't have access to the system or environment where it was developed. The libraries used are quite standard so I don't think the python version should be so relevant. I think any before 3.10 should work.
